### ISSUE TITLE
No release 

### ISSUE THREAD

**Issue by Josef212** [dibu13/Qt-2D-Painter#2]
Please would be greate to have a release with the latest changes

**Comment by CapitanLiteral** [comment]
This is a duplicated issue, check issues before asking. Check it [here](https://github.com/dibu13/Qt-2D-Painter/issues/1) 😉

**Comment by Josef212** [comment]
Already saw it, but since there was no answer from the creator I decided to create a new issue to increase the pressure. This way may be the creator will upload a release. :grin:

**Comment by cumus** [comment]
Thanks for the feedback. Its scheduled for next week. Please be patient. We are working as slow as possible.

**Comment by Josef212** [comment]
Good to hear that. Thanks, 10/10 to the collaborators will recomend on my reviews. Fan since first day :wink:

**Comment by CapitanLiteral** [comment]
I'm happy to hear that! 😊😊

**Comment by cumus** [comment]
The new release is now available [here](https://github.com/UndistinguishedFellows/God-s_Tale). Check it out!

**Comment by CapitanLiteral** [comment]
😮
